openapi: 3.0.0
info:
  title: Real-Time soil moisture level.
  description: TBA
  version: 0.0.1
servers:
- url: /moisture/v1
paths:
  /sensor/latest:
    get:
      summary: "Returns the latest sensor readings (light, temperature, soil moisture)."
      operationId: controller_get_latest_sensor_data
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SensorData"
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /sensor/aggregate:
    get:
      summary: Returns a list of average sensor readings of every user-specified interval
        for the last user-specified days.
      operationId: controller_aggregate_sensor_data
      parameters:
      - name: days
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: hours
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SensorData"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /weather/latest:
    get:
      summary: Returns the latest weather data from open-meteo
      operationId: controller_get_latest_weather_data
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WeatherData"
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /weather/aggregate:
    get:
      summary: Returns a list of average sensor readings of every user-specified interval
        for the last user-specified days.
      operationId: controller_aggregate_weather_data
      parameters:
      - name: days
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: hours
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeatherData"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /predictmoisture/{moisture}:
    get:
      summary: Get the prediction of soil moisture.
      operationId: controller_moisture_prediction
      parameters:
      - name: moisture
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: number
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PredictMoisture"
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    SensorData:
      type: object
      properties:
        read_time:
          type: string
        light:
          type: number
        temperature:
          type: number
        soil_moisture:
          type: number
      example:
        read_time: read_time
        light: 0.8008281904610115
        temperature: 6.027456183070403
        soil_moisture: 1.4658129805029452
    WeatherData:
      type: object
      properties:
        read_time:
          type: string
        humidity:
          type: number
        precipitation:
          type: number
        temperature:
          type: number
        cloud_cover:
          type: number
      example:
        precipitation: 6.027456183070403
        read_time: read_time
        temperature: 1.4658129805029452
        cloud_cover: 5.962133916683182
        humidity: 0.8008281904610115
    SoilMoisture:
      type: object
      properties:
        read_time:
          type: string
        soil_moisture:
          type: number
      example:
        read_time: read_time
        soil_moisture: 0.8008281904610115
    PredictMoisture:
      type: object
      properties:
        duration:
          type: string
        predictions:
          type: array
          items:
            $ref: "#/components/schemas/SoilMoisture"
      example:
        duration: duration
        predictions:
        - read_time: read_time
          soil_moisture: 0.8008281904610115
        - read_time: read_time
          soil_moisture: 0.8008281904610115

